#backend/app/storage/base.py
from abc import ABC, abstractmethod
from backend.app.models.document import Document
from backend.app.models.posting import Posting


class DocumentRepository(ABC):
    @abstractmethod
    def save(self, doc: Document) -> None: ...
    @abstractmethod
    def get(self, doc_id: int) -> Document | None: ...
    @abstractmethod
    def all(self) -> dict[int, Document]: ...
    @abstractmethod
    def exists_by_path(self, path: str) -> bool: ...
    @abstractmethod
    def next_id(self) -> int: ...


class IndexRepository(ABC):
    @abstractmethod
    def add_posting(self, term: str, postings: list[Posting]) -> None: ...
    @abstractmethod
    def get_postings(self, term: str) -> list[Posting]: ...
    @abstractmethod
    def vocabulary_size(self) -> int: ...
    @abstractmethod
    def clear(self) -> None: ...
    @abstractmethod
    def document_frequency(self, term: str) -> int: ...
    @abstractmethod
    def add_document_terms(self, doc_id: int, term_freqs: dict[str, int]) -> None: ...
    @abstractmethod
    def get_document_terms(self, doc_id: int) -> dict[str, int]: ...


class ConfigRepository(ABC):
    @abstractmethod
    def get(self) -> dict | None: ...
    @abstractmethod
    def save(self, config: dict) -> None: ...


class DirectoryRepository(ABC):
    @abstractmethod
    def list(self) -> list[dict]: ...
    @abstractmethod
    def add(self, path: str) -> dict: ...
    @abstractmethod
    def delete(self, dir_id: int) -> None: ...